### ISSUE TITLE
No Texture for Rune Assembler

### ISSUE THREAD

**Issue by Holladiewal** [ParadoxCodersTeam/Botanic-Energistics#10]

**Comment by Holladiewal** [comment]
Did a simple Texture for Rune Assembler and AEDaisy
![2015-10-08_15 50 15](https://cloud.githubusercontent.com/assets/7950771/10368229/9a8173ec-6dd4-11e5-9124-0de92ccb7551.png)

**Comment by Minothor** [comment]
do you guys want any 3D renderings done for these?
e.g. datavines:
![2015-10-08_20 57 55](https://cloud.githubusercontent.com/assets/2125437/10378190/6b6f74ca-6dff-11e5-984f-ef7ad619fa8e.png)
(still sorting out all the angles and directions)
