### ISSUE TITLE
Project files and Metadata in Repo

### ISSUE THREAD

**Issue by Minothor** [ParadoxCodersTeam/Botanic-Energistics#17]
Guys, please could we keep the Repo clear of any metadata and IDE related files?
I've been keeping my .gitignore updated and being careful not to let Eclipse artifacts leach in to the project files whenever they appear.
(Still got work to do on that, since Sourcetree doesn't seem to care that I've told it to ignore those files)

**Comment by Minothor** [comment]
(because "fix it yourself" just sounds rude to be honest)

**Comment by BackSpace47** [comment]
Sounds great
