### ISSUE TITLE
Build Control

### ISSUE THREAD

**Issue by Minothor** [ParadoxCodersTeam/Botanic-Energistics#18]
Would this be of any use to us?
https://travis-ci.org/
(found it while reading through a module's documentation at work, looks pretty nifty for FOSS)

**Comment by wolfcomp** [comment]
It would be cool to have one running

**Comment by Holladiewal** [comment]
If thought of setting up an teamcity servee, but we could also use Travis if you want to

**Comment by Minothor** [comment]
Which one would you say is easier to get going quickly?

**Comment by Holladiewal** [comment]
I've played with a local teamcity installation, so I could get the teamcity up in the same time as the Travis one..

Von meinem Sony Xperia™-Smartphone gesendet

**Comment by Minothor** [comment]
For Added Deliciousness (and project management):
https://waffle.io/ParadoxCodersTeam/Botanic-Energistics
That hooks into github and presents all our github issues and tasksin a visual, draggable Kanban style manner.
(oh and I'm typing this from within it)
