### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by Vazkii** [ParadoxCodersTeam/Botanic-Energistics#2]
Hello.

Starting this project, I'd assume you already knew you'd encounter some sort of backlash. First and foremost, I do not condone nor like this concept for an addon (I've been vocal about poor integration in botania before (see Technomancy) and this is another case) but I don't have any right or power to stop you from doing it. And even if I did, I wouldn't. We'd be losing on a potential mod that could improve many people's gameplay experience in the long run purely for the sake of my ego.

I do however, have some requests I'd like you to abide by. These are, of course, not stipulations or orders, as I, again, do not have the power or desire to enforce these, but purely requests, from a person who I do assume you respect in some way, otherwise I really can only come to the conclusion that this addon was made out of spite, one I don't want to arrive at.

The first request is to not add any methods of storing, transferring or directly utilizing mana through the ME network. While the mod already obsoletes a portion of botania, this goes further, by making the whole power system optional and subpar.

The second request is far more important, which is to be reasonable while making this, understand what you're adding and what implications it might have. Have a look through [this article](http://vazkii.us/uncategorized/stuff-you-wont-see-in-botania/) I wrote a while ago. Perhaps take some time to try playing botania without other mods to interfere (you can find the [official modpack here](http://minecraft.curseforge.com/modpacks/233293-botania-skyblock-the-modpack-the-mod-the-modpack), if you want something to kickstart that) so you can understand better how the dynamic of the mod functions and how all the various features interlink to create an overall cohesive experience.

From what I can understand of the small chunks of code already available here, this mod will integrate with AE by adding new pattern and crafting methods for the botania crafting systems. While that does, effectively remove part of the challenge in botania (have you tried making an automatic runic crafting system? It's pretty hard!), it doesn't obsolete any concrete part of the mod per se, but rather, one of the things the mod enables you to do. I don't like it, but to me, it's one of the lesser evils. Please be reasonable with what you choose to turn this into.

**Comment by Minothor** [comment]
Hi Vazkii, thanks for taking the time to weigh in on this, if I understand this correctly, the following remains "acceptable" (using the term loosely) and in compliance with your guidelines:
- Petal Apothecary (crafts without Mana)
- Redstring interfacing

We had hoped to include some sort of Spark/Spreader integration (having a type of terminal act as a "virtual pool" but seeing your request, yeah that probably won't be an option.

I'd like to clarify though, this is in no way meant to spite or annoy you.
We are all fans of both mods and wanted to see if we could bridge them in a fitting manner.
The guidelines here will give us a lot to re-evaluate from our initial plan, but part of every game and mod is design. Arguably, one of the most important parts.
So we will put in the work necessary to make the design suitable and fitting for both the authors of the original mods and the communities that play them.

**Comment by Vazkii** [comment]
I'll choose not to comment further as not to enter a state of "but he said this!". My original requests still stand.
