### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vankka** [ParadoxCodersTeam/Botanic-Energistics#21]
Crash when a comparator is placed next to the wired daisy

**Comment by Vankka** [comment]
Same thing with reqular redstone

**Comment by Holladiewal** [comment]
Sorry that I haven't seen your issues, but please for every crash give me the crash log or I can't do anything

**Comment by Vankka** [comment]
> ---- Minecraft Crash Report ----
> // I just don't know what went wrong :(
> 
> Time: 13.7.2016 15:33
> Description: Ticking block entity
> 
> java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
>   at appeng.tile.events.AETileEventHandler.tick(AETileEventHandler.java:62)
>   at appeng.tile.AEBaseTile.func_145845_h(AEBaseTile.java:181)
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
>   at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.reflect.InvocationTargetException
>   at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at appeng.tile.events.AETileEventHandler.tick(AETileEventHandler.java:50)
>   ... 12 more
> Caused by: java.lang.NullPointerException
>   at pct.botanic.energistics.blocks.tile.TileAEDaisy.onTick(TileAEDaisy.java:128)
>   ... 16 more
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at appeng.tile.events.AETileEventHandler.tick(AETileEventHandler.java:62)
>   at appeng.tile.AEBaseTile.func_145845_h(AEBaseTile.java:181)
> 
> -- Block entity being ticked --
> Details:
>   Name: tile.aedaisy // pct.botanic.energistics.blocks.tile.TileAEDaisy
>   Block type: ID #704 (tile.aedaisy // pct.botanic.energistics.blocks.AEPureDaisy)
>   Block data value: 0 / 0x0 / 0b0000
>   Block location: World: (14,56,564), Chunk: (at 14,3,4 in 0,35; contains blocks 0,0,560 to 15,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
>   Actual block type: ID #704 (tile.aedaisy // pct.botanic.energistics.blocks.AEPureDaisy)
>   Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
>   at net.minecraft.world.World.func_72939_s(World.java:1939)
> 
> -- Affected level --
> Details:
>   Level name: MpServer
>   All players: 1 total; [EntityClientPlayerMP['Vankka'/1, l='MpServer', x=14,53, y=60,16, z=564,33]]
>   Chunk stats: MultiplayerChunkCache: 289, 289
>   Level seed: 0
>   Level generator: ID 01 - flat, ver 0. Features enabled: false
>   Level generator options: 
>   Level spawn location: World: (25,4,559), Chunk: (at 9,0,15 in 1,34; contains blocks 16,0,544 to 31,255,559), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
>   Level time: 508 game time, 508 day time
>   Level dimension: 0
>   Level storage version: 0x00000 - Unknown?
>   Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
>   Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
>   Forced entities: 1 total; [EntityClientPlayerMP['Vankka'/1, l='MpServer', x=14,53, y=60,16, z=564,33]]
>   Retry entities: 0 total; []
>   Server brand: fml,forge
>   Server type: Integrated singleplayer server
> Stacktrace:
>   at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
>   at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.7.10
>   Operating System: Windows 10 (amd64) version 10.0
>   Java Version: 1.8.0_25, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 1029509312 bytes (981 MB) / 1438646272 bytes (1372 MB) up to 3817865216 bytes (3641 MB)
>   JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
>   AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
>   FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 11 mods loaded, 11 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
>   UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
>   UCHIJAAAA   appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
>   UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
>   UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
>   UCHIJAAAA   appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
>   UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
>   UCHIJAAAA   Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
>   UCHIJAAAA   botanicenergistics{@version@} [Botanic-Energistics](BotanicEnergistics-0.2.6.jar) 
>   UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
>   GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.69' Renderer: 'GeForce GTX 960/PCIe/SSE2'
>   AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
>   AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
>   Launched Version: forge-10.13.4.1614
>   LWJGL: 2.9.1
>   OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.69, NVIDIA Corporation
>   GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
>   Is Modded: Definitely; Client brand changed to 'fml,forge'
>   Type: Client (map_client.txt)
>   Resource Packs: []
>   Current Language: English (US)
>   Profiler Position: N/A (disabled)
>   Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   Anisotropic Filtering: Off (1)
